# Wordpress Docker Stack using Traefik Reverse Proxy
# Should work version '2'
version: '3.7'

services:
  db:
    image: mysql:5.7
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
    labels:
      - "traefik.enable=false"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
  wp:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - backend
      - frontend
    restart: always
    labels:
      - "traefik.docker.network=traefik_webgateway"
      - "traefik.frontend.rule=Host:${WP_HOST_NAME}"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
  fb:
    depends_on:
      - wp
    image: filebrowser/filebrowser
    volumes:
      - ./wp:/srv
      - ./config/.filebrowser.json:/.filebrowser.json
      - ./fb/filebrowser.db:/database.db
    networks:
      - frontend
    restart: always
    labels:
      - "traefik.docker.network=traefik_webgateway"
      - "traefik.frontend.rule=Host:${FB_HOST_NAME}"
volumes:
  db: {}

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: traefik_webgateway